// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promociones.Infrastructure;

namespace Promociones.Infrastructure.Migrations
{
    [DbContext(typeof(PromocionesDbContext))]
    partial class PromocionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Promociones.Domain.Entities.Promocion", b =>
                {
                    b.Property<int>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<DateTime?>("FechaModificacion");

                    b.Property<int?>("MaxCantidadDeCuotas");

                    b.Property<double?>("PorcentajeDescuento")
                        .HasColumnType("float");

                    b.Property<string>("StrEntidadFinancieraId");

                    b.Property<string>("StrMedioPagoIds");

                    b.Property<string>("StrProductoCategoriaIds");

                    b.Property<string>("StrTipoMedioPagoId");

                    b.HasKey("IdPromotion");

                    b.ToTable("Promociones");
                });
#pragma warning restore 612, 618
        }
    }
}
